export interface EmojiItem {
  emoji: string;
  name: string;
  keywords?: string[];
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiItem[];
}

export const emojiCategories: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys & People',
    icon: '😀',
    emojis: [
      { emoji: '😀', name: 'grinning face', keywords: ['happy', 'smile'] },
      { emoji: '😃', name: 'grinning face with big eyes', keywords: ['happy', 'smile'] },
      { emoji: '😄', name: 'grinning face with smiling eyes', keywords: ['happy', 'smile'] },
      { emoji: '😁', name: 'beaming face with smiling eyes', keywords: ['happy', 'grin'] },
      { emoji: '😆', name: 'grinning squinting face', keywords: ['laugh', 'lol'] },
      { emoji: '😅', name: 'grinning face with sweat', keywords: ['nervous', 'sweat'] },
      { emoji: '🤣', name: 'rolling on the floor laughing', keywords: ['rofl', 'laugh'] },
      { emoji: '😂', name: 'face with tears of joy', keywords: ['lol', 'laugh', 'cry'] },
      { emoji: '🙂', name: 'slightly smiling face', keywords: ['smile'] },
      { emoji: '🙃', name: 'upside-down face', keywords: ['silly', 'sarcasm'] },
      { emoji: '😉', name: 'winking face', keywords: ['wink', 'flirt'] },
      { emoji: '😊', name: 'smiling face with smiling eyes', keywords: ['blush', 'happy'] },
      { emoji: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent'] },
      { emoji: '🥰', name: 'smiling face with hearts', keywords: ['love', 'adore'] },
      { emoji: '😍', name: 'smiling face with heart-eyes', keywords: ['love', 'crush'] },
      { emoji: '🤩', name: 'star-struck', keywords: ['wow', 'amazing'] },
      { emoji: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love'] },
      { emoji: '😗', name: 'kissing face', keywords: ['kiss'] },
      { emoji: '😚', name: 'kissing face with closed eyes', keywords: ['kiss'] },
      { emoji: '😙', name: 'kissing face with smiling eyes', keywords: ['kiss'] },
      { emoji: '🥲', name: 'smiling face with tear', keywords: ['happy', 'cry'] },
      { emoji: '😋', name: 'face savoring food', keywords: ['yum', 'delicious'] },
      { emoji: '😛', name: 'face with tongue', keywords: ['tongue', 'silly'] },
      { emoji: '😜', name: 'winking face with tongue', keywords: ['silly', 'wink'] },
      { emoji: '🤪', name: 'zany face', keywords: ['crazy', 'silly'] },
      { emoji: '😝', name: 'squinting face with tongue', keywords: ['tongue', 'silly'] },
      { emoji: '🤑', name: 'money-mouth face', keywords: ['money', 'rich'] },
      { emoji: '🤗', name: 'smiling face with open hands', keywords: ['hug', 'warm'] },
      { emoji: '🤭', name: 'face with hand over mouth', keywords: ['oops', 'secret'] },
      { emoji: '🤫', name: 'shushing face', keywords: ['quiet', 'secret'] },
      { emoji: '🤔', name: 'thinking face', keywords: ['think', 'hmm'] },
      { emoji: '🤐', name: 'zipper-mouth face', keywords: ['quiet', 'secret'] },
      { emoji: '🤨', name: 'face with raised eyebrow', keywords: ['suspicious', 'skeptical'] },
      { emoji: '😐', name: 'neutral face', keywords: ['neutral', 'meh'] },
      { emoji: '😑', name: 'expressionless face', keywords: ['blank', 'meh'] },
      { emoji: '😶', name: 'face without mouth', keywords: ['silent', 'quiet'] },
      { emoji: '😏', name: 'smirking face', keywords: ['smirk', 'sly'] },
      { emoji: '😒', name: 'unamused face', keywords: ['bored', 'unimpressed'] },
      { emoji: '🙄', name: 'face with rolling eyes', keywords: ['eyeroll', 'whatever'] },
      { emoji: '😬', name: 'grimacing face', keywords: ['grimace', 'awkward'] },
      { emoji: '😮‍💨', name: 'face exhaling', keywords: ['sigh', 'relief'] },
      { emoji: '🤥', name: 'lying face', keywords: ['lie', 'pinocchio'] },
      { emoji: '😌', name: 'relieved face', keywords: ['relief', 'calm'] },
      { emoji: '😔', name: 'pensive face', keywords: ['sad', 'thoughtful'] },
      { emoji: '😪', name: 'sleepy face', keywords: ['tired', 'sleep'] },
      { emoji: '🤤', name: 'drooling face', keywords: ['drool', 'hungry'] },
      { emoji: '😴', name: 'sleeping face', keywords: ['sleep', 'zzz'] },
      { emoji: '😷', name: 'face with medical mask', keywords: ['sick', 'mask'] },
      { emoji: '🤒', name: 'face with thermometer', keywords: ['sick', 'fever'] },
      { emoji: '🤕', name: 'face with head-bandage', keywords: ['hurt', 'injured'] },
      { emoji: '🤢', name: 'nauseated face', keywords: ['sick', 'gross'] },
      { emoji: '🤮', name: 'face vomiting', keywords: ['sick', 'gross'] },
      { emoji: '🤧', name: 'sneezing face', keywords: ['sneeze', 'sick'] },
      { emoji: '🥵', name: 'hot face', keywords: ['hot', 'sweating'] },
      { emoji: '🥶', name: 'cold face', keywords: ['cold', 'freezing'] },
      { emoji: '🥴', name: 'woozy face', keywords: ['dizzy', 'drunk'] },
      { emoji: '😵', name: 'face with crossed-out eyes', keywords: ['dizzy', 'dead'] },
      { emoji: '🤯', name: 'exploding head', keywords: ['mindblown', 'wow'] },
      { emoji: '🤠', name: 'cowboy hat face', keywords: ['cowboy', 'western'] },
      { emoji: '🥳', name: 'partying face', keywords: ['party', 'celebrate'] },
      { emoji: '🥸', name: 'disguised face', keywords: ['disguise', 'incognito'] },
      { emoji: '😎', name: 'smiling face with sunglasses', keywords: ['cool', 'sunglasses'] },
      { emoji: '🤓', name: 'nerd face', keywords: ['nerd', 'geek'] },
      { emoji: '🧐', name: 'face with monocle', keywords: ['monocle', 'fancy'] },
      { emoji: '😕', name: 'confused face', keywords: ['confused', 'unsure'] },
      { emoji: '😟', name: 'worried face', keywords: ['worried', 'concerned'] },
      { emoji: '🙁', name: 'slightly frowning face', keywords: ['sad', 'frown'] },
      { emoji: '☹️', name: 'frowning face', keywords: ['sad', 'unhappy'] },
      { emoji: '😮', name: 'face with open mouth', keywords: ['surprised', 'wow'] },
      { emoji: '😯', name: 'hushed face', keywords: ['surprised', 'quiet'] },
      { emoji: '😲', name: 'astonished face', keywords: ['shocked', 'wow'] },
      { emoji: '😳', name: 'flushed face', keywords: ['embarrassed', 'blush'] },
      { emoji: '🥺', name: 'pleading face', keywords: ['please', 'puppy eyes'] },
      { emoji: '😦', name: 'frowning face with open mouth', keywords: ['sad', 'shocked'] },
      { emoji: '😧', name: 'anguished face', keywords: ['anguish', 'shocked'] },
      { emoji: '😨', name: 'fearful face', keywords: ['fear', 'scared'] },
      { emoji: '😰', name: 'anxious face with sweat', keywords: ['nervous', 'anxious'] },
      { emoji: '😥', name: 'sad but relieved face', keywords: ['sad', 'relieved'] },
      { emoji: '😢', name: 'crying face', keywords: ['cry', 'sad', 'tear'] },
      { emoji: '😭', name: 'loudly crying face', keywords: ['cry', 'sob', 'sad'] },
      { emoji: '😱', name: 'face screaming in fear', keywords: ['scream', 'scared'] },
      { emoji: '😖', name: 'confounded face', keywords: ['confused', 'frustrated'] },
      { emoji: '😣', name: 'persevering face', keywords: ['struggle', 'persevere'] },
      { emoji: '😞', name: 'disappointed face', keywords: ['disappointed', 'sad'] },
      { emoji: '😓', name: 'downcast face with sweat', keywords: ['sad', 'sweat'] },
      { emoji: '😩', name: 'weary face', keywords: ['tired', 'weary'] },
      { emoji: '😫', name: 'tired face', keywords: ['tired', 'exhausted'] },
      { emoji: '🥱', name: 'yawning face', keywords: ['yawn', 'tired', 'bored'] },
      { emoji: '😤', name: 'face with steam from nose', keywords: ['angry', 'triumph'] },
      { emoji: '😡', name: 'enraged face', keywords: ['angry', 'mad'] },
      { emoji: '😠', name: 'angry face', keywords: ['angry', 'mad'] },
      { emoji: '🤬', name: 'face with symbols on mouth', keywords: ['angry', 'swearing'] },
      { emoji: '😈', name: 'smiling face with horns', keywords: ['devil', 'evil'] },
      { emoji: '👿', name: 'angry face with horns', keywords: ['devil', 'evil', 'angry'] },
      { emoji: '💀', name: 'skull', keywords: ['dead', 'death', 'skull'] },
      { emoji: '☠️', name: 'skull and crossbones', keywords: ['dead', 'danger'] },
      { emoji: '💩', name: 'pile of poo', keywords: ['poop', 'shit'] },
      { emoji: '🤡', name: 'clown face', keywords: ['clown', 'joker'] },
      { emoji: '👹', name: 'ogre', keywords: ['monster', 'ogre'] },
      { emoji: '👺', name: 'goblin', keywords: ['monster', 'goblin'] },
      { emoji: '👻', name: 'ghost', keywords: ['ghost', 'halloween'] },
      { emoji: '👽', name: 'alien', keywords: ['alien', 'ufo'] },
      { emoji: '👾', name: 'alien monster', keywords: ['alien', 'game'] },
      { emoji: '🤖', name: 'robot', keywords: ['robot', 'bot'] },
    ],
  },
  {
    id: 'gestures',
    label: 'Gestures & Body',
    icon: '👋',
    emojis: [
      { emoji: '👋', name: 'waving hand', keywords: ['wave', 'hello', 'bye'] },
      { emoji: '🤚', name: 'raised back of hand', keywords: ['hand', 'stop'] },
      { emoji: '🖐️', name: 'hand with fingers splayed', keywords: ['hand', 'five'] },
      { emoji: '✋', name: 'raised hand', keywords: ['stop', 'high five'] },
      { emoji: '🖖', name: 'vulcan salute', keywords: ['spock', 'star trek'] },
      { emoji: '👌', name: 'ok hand', keywords: ['ok', 'perfect'] },
      { emoji: '🤌', name: 'pinched fingers', keywords: ['italian', 'perfect'] },
      { emoji: '✌️', name: 'victory hand', keywords: ['peace', 'victory'] },
      { emoji: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope'] },
      { emoji: '🤟', name: 'love-you gesture', keywords: ['love', 'rock'] },
      { emoji: '🤘', name: 'sign of the horns', keywords: ['rock', 'metal'] },
      { emoji: '🤙', name: 'call me hand', keywords: ['call', 'shaka'] },
      { emoji: '👈', name: 'backhand index pointing left', keywords: ['left', 'point'] },
      { emoji: '👉', name: 'backhand index pointing right', keywords: ['right', 'point'] },
      { emoji: '👆', name: 'backhand index pointing up', keywords: ['up', 'point'] },
      { emoji: '🖕', name: 'middle finger', keywords: ['middle finger', 'rude'] },
      { emoji: '👇', name: 'backhand index pointing down', keywords: ['down', 'point'] },
      { emoji: '☝️', name: 'index pointing up', keywords: ['up', 'point', 'one'] },
      { emoji: '👍', name: 'thumbs up', keywords: ['like', 'good', 'yes'] },
      { emoji: '👎', name: 'thumbs down', keywords: ['dislike', 'bad', 'no'] },
      { emoji: '✊', name: 'raised fist', keywords: ['fist', 'power'] },
      { emoji: '👊', name: 'oncoming fist', keywords: ['punch', 'fist'] },
      { emoji: '🤛', name: 'left-facing fist', keywords: ['fist bump'] },
      { emoji: '🤜', name: 'right-facing fist', keywords: ['fist bump'] },
      { emoji: '👏', name: 'clapping hands', keywords: ['clap', 'applause'] },
      { emoji: '🙌', name: 'raising hands', keywords: ['celebrate', 'hooray'] },
      { emoji: '👐', name: 'open hands', keywords: ['open', 'hug'] },
      { emoji: '🤲', name: 'palms up together', keywords: ['pray', 'please'] },
      { emoji: '🤝', name: 'handshake', keywords: ['deal', 'agreement'] },
      { emoji: '🙏', name: 'folded hands', keywords: ['pray', 'please', 'thanks'] },
      { emoji: '✍️', name: 'writing hand', keywords: ['write', 'pen'] },
      { emoji: '💅', name: 'nail polish', keywords: ['nails', 'manicure'] },
      { emoji: '🤳', name: 'selfie', keywords: ['selfie', 'photo'] },
      { emoji: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle'] },
      { emoji: '🦾', name: 'mechanical arm', keywords: ['robot', 'arm'] },
      { emoji: '🦿', name: 'mechanical leg', keywords: ['robot', 'leg'] },
      { emoji: '🦵', name: 'leg', keywords: ['leg', 'kick'] },
      { emoji: '🦶', name: 'foot', keywords: ['foot', 'kick'] },
      { emoji: '👂', name: 'ear', keywords: ['ear', 'listen'] },
      { emoji: '🦻', name: 'ear with hearing aid', keywords: ['ear', 'deaf'] },
      { emoji: '👃', name: 'nose', keywords: ['nose', 'smell'] },
      { emoji: '🧠', name: 'brain', keywords: ['brain', 'smart'] },
      { emoji: '🫀', name: 'anatomical heart', keywords: ['heart', 'organ'] },
      { emoji: '🫁', name: 'lungs', keywords: ['lungs', 'breathe'] },
      { emoji: '🦷', name: 'tooth', keywords: ['tooth', 'dentist'] },
      { emoji: '🦴', name: 'bone', keywords: ['bone', 'skeleton'] },
      { emoji: '👀', name: 'eyes', keywords: ['eyes', 'look', 'see'] },
      { emoji: '👁️', name: 'eye', keywords: ['eye', 'look'] },
      { emoji: '👅', name: 'tongue', keywords: ['tongue', 'taste'] },
      { emoji: '👄', name: 'mouth', keywords: ['mouth', 'lips', 'kiss'] },
    ],
  },
  {
    id: 'hearts',
    label: 'Hearts & Love',
    icon: '❤️',
    emojis: [
      { emoji: '❤️', name: 'red heart', keywords: ['love', 'heart'] },
      { emoji: '🧡', name: 'orange heart', keywords: ['love', 'heart', 'orange'] },
      { emoji: '💛', name: 'yellow heart', keywords: ['love', 'heart', 'yellow'] },
      { emoji: '💚', name: 'green heart', keywords: ['love', 'heart', 'green'] },
      { emoji: '💙', name: 'blue heart', keywords: ['love', 'heart', 'blue'] },
      { emoji: '💜', name: 'purple heart', keywords: ['love', 'heart', 'purple'] },
      { emoji: '🖤', name: 'black heart', keywords: ['love', 'heart', 'black'] },
      { emoji: '🤍', name: 'white heart', keywords: ['love', 'heart', 'white'] },
      { emoji: '🤎', name: 'brown heart', keywords: ['love', 'heart', 'brown'] },
      { emoji: '💔', name: 'broken heart', keywords: ['heartbreak', 'sad'] },
      { emoji: '❣️', name: 'heart exclamation', keywords: ['heart', 'exclamation'] },
      { emoji: '💕', name: 'two hearts', keywords: ['love', 'hearts'] },
      { emoji: '💞', name: 'revolving hearts', keywords: ['love', 'hearts'] },
      { emoji: '💓', name: 'beating heart', keywords: ['love', 'heart', 'beat'] },
      { emoji: '💗', name: 'growing heart', keywords: ['love', 'heart'] },
      { emoji: '💖', name: 'sparkling heart', keywords: ['love', 'heart', 'sparkle'] },
      { emoji: '💘', name: 'heart with arrow', keywords: ['love', 'cupid'] },
      { emoji: '💝', name: 'heart with ribbon', keywords: ['love', 'gift'] },
      { emoji: '💟', name: 'heart decoration', keywords: ['heart', 'decoration'] },
      { emoji: '☮️', name: 'peace symbol', keywords: ['peace'] },
      { emoji: '✝️', name: 'latin cross', keywords: ['cross', 'christian'] },
      { emoji: '☯️', name: 'yin yang', keywords: ['yin yang', 'balance'] },
      { emoji: '🕊️', name: 'dove', keywords: ['peace', 'dove'] },
      { emoji: '💌', name: 'love letter', keywords: ['love', 'letter', 'mail'] },
      { emoji: '💋', name: 'kiss mark', keywords: ['kiss', 'lips'] },
      { emoji: '💍', name: 'ring', keywords: ['ring', 'wedding', 'engagement'] },
      { emoji: '💎', name: 'gem stone', keywords: ['diamond', 'gem', 'jewel'] },
    ],
  },
  {
    id: 'animals',
    label: 'Animals & Nature',
    icon: '🐶',
    emojis: [
      { emoji: '🐶', name: 'dog face', keywords: ['dog', 'puppy', 'pet'] },
      { emoji: '🐱', name: 'cat face', keywords: ['cat', 'kitten', 'pet'] },
      { emoji: '🐭', name: 'mouse face', keywords: ['mouse', 'rodent'] },
      { emoji: '🐹', name: 'hamster', keywords: ['hamster', 'pet'] },
      { emoji: '🐰', name: 'rabbit face', keywords: ['rabbit', 'bunny'] },
      { emoji: '🦊', name: 'fox', keywords: ['fox', 'clever'] },
      { emoji: '🐻', name: 'bear', keywords: ['bear', 'animal'] },
      { emoji: '🐼', name: 'panda', keywords: ['panda', 'bear'] },
      { emoji: '🐨', name: 'koala', keywords: ['koala', 'australia'] },
      { emoji: '🐯', name: 'tiger face', keywords: ['tiger', 'cat'] },
      { emoji: '🦁', name: 'lion', keywords: ['lion', 'king'] },
      { emoji: '🐮', name: 'cow face', keywords: ['cow', 'moo'] },
      { emoji: '🐷', name: 'pig face', keywords: ['pig', 'oink'] },
      { emoji: '🐸', name: 'frog', keywords: ['frog', 'green'] },
      { emoji: '🐵', name: 'monkey face', keywords: ['monkey', 'ape'] },
      { emoji: '🙈', name: 'see-no-evil monkey', keywords: ['monkey', 'see no evil'] },
      { emoji: '🙉', name: 'hear-no-evil monkey', keywords: ['monkey', 'hear no evil'] },
      { emoji: '🙊', name: 'speak-no-evil monkey', keywords: ['monkey', 'speak no evil'] },
      { emoji: '🐔', name: 'chicken', keywords: ['chicken', 'bird'] },
      { emoji: '🐧', name: 'penguin', keywords: ['penguin', 'bird'] },
      { emoji: '🐦', name: 'bird', keywords: ['bird', 'tweet'] },
      { emoji: '🦆', name: 'duck', keywords: ['duck', 'quack'] },
      { emoji: '🦅', name: 'eagle', keywords: ['eagle', 'bird'] },
      { emoji: '🦉', name: 'owl', keywords: ['owl', 'wise'] },
      { emoji: '🦇', name: 'bat', keywords: ['bat', 'halloween'] },
      { emoji: '🐺', name: 'wolf', keywords: ['wolf', 'howl'] },
      { emoji: '🐗', name: 'boar', keywords: ['boar', 'pig'] },
      { emoji: '🐴', name: 'horse face', keywords: ['horse', 'pony'] },
      { emoji: '🦄', name: 'unicorn', keywords: ['unicorn', 'magic'] },
      { emoji: '🐝', name: 'honeybee', keywords: ['bee', 'honey'] },
      { emoji: '🐛', name: 'bug', keywords: ['bug', 'caterpillar'] },
      { emoji: '🦋', name: 'butterfly', keywords: ['butterfly', 'beautiful'] },
      { emoji: '🐌', name: 'snail', keywords: ['snail', 'slow'] },
      { emoji: '🐞', name: 'lady beetle', keywords: ['ladybug', 'bug'] },
      { emoji: '🐜', name: 'ant', keywords: ['ant', 'bug'] },
      { emoji: '🦟', name: 'mosquito', keywords: ['mosquito', 'bug'] },
      { emoji: '🐢', name: 'turtle', keywords: ['turtle', 'slow'] },
      { emoji: '🐍', name: 'snake', keywords: ['snake', 'reptile'] },
      { emoji: '🦎', name: 'lizard', keywords: ['lizard', 'reptile'] },
      { emoji: '🦕', name: 'sauropod', keywords: ['dinosaur', 'dino'] },
      { emoji: '🦖', name: 't-rex', keywords: ['dinosaur', 'trex'] },
      { emoji: '🐳', name: 'spouting whale', keywords: ['whale', 'ocean'] },
      { emoji: '🐬', name: 'dolphin', keywords: ['dolphin', 'ocean'] },
      { emoji: '🦈', name: 'shark', keywords: ['shark', 'ocean'] },
      { emoji: '🐙', name: 'octopus', keywords: ['octopus', 'ocean'] },
      { emoji: '🦑', name: 'squid', keywords: ['squid', 'ocean'] },
      { emoji: '🦞', name: 'lobster', keywords: ['lobster', 'seafood'] },
      { emoji: '🦀', name: 'crab', keywords: ['crab', 'seafood'] },
      { emoji: '🐡', name: 'blowfish', keywords: ['fish', 'ocean'] },
      { emoji: '🐠', name: 'tropical fish', keywords: ['fish', 'tropical'] },
      { emoji: '🌸', name: 'cherry blossom', keywords: ['flower', 'spring', 'pink'] },
      { emoji: '🌺', name: 'hibiscus', keywords: ['flower', 'tropical'] },
      { emoji: '🌻', name: 'sunflower', keywords: ['flower', 'sun'] },
      { emoji: '🌹', name: 'rose', keywords: ['flower', 'love', 'red'] },
      { emoji: '🌷', name: 'tulip', keywords: ['flower', 'spring'] },
      { emoji: '🌿', name: 'herb', keywords: ['plant', 'green'] },
      { emoji: '🍀', name: 'four leaf clover', keywords: ['luck', 'clover'] },
      { emoji: '🌴', name: 'palm tree', keywords: ['tree', 'tropical'] },
      { emoji: '🌵', name: 'cactus', keywords: ['cactus', 'desert'] },
      { emoji: '🌊', name: 'water wave', keywords: ['wave', 'ocean', 'surf'] },
      { emoji: '🌈', name: 'rainbow', keywords: ['rainbow', 'colorful'] },
      { emoji: '⭐', name: 'star', keywords: ['star', 'night'] },
      { emoji: '🌟', name: 'glowing star', keywords: ['star', 'sparkle'] },
      { emoji: '✨', name: 'sparkles', keywords: ['sparkle', 'magic'] },
      { emoji: '🌙', name: 'crescent moon', keywords: ['moon', 'night'] },
      { emoji: '☀️', name: 'sun', keywords: ['sun', 'sunny', 'day'] },
      { emoji: '⛅', name: 'sun behind cloud', keywords: ['cloud', 'partly cloudy'] },
      { emoji: '🌧️', name: 'cloud with rain', keywords: ['rain', 'weather'] },
      { emoji: '⛈️', name: 'cloud with lightning and rain', keywords: ['storm', 'thunder'] },
      { emoji: '❄️', name: 'snowflake', keywords: ['snow', 'cold', 'winter'] },
      { emoji: '🔥', name: 'fire', keywords: ['fire', 'hot', 'flame'] },
    ],
  },
  {
    id: 'food',
    label: 'Food & Drink',
    icon: '🍕',
    emojis: [
      { emoji: '🍎', name: 'red apple', keywords: ['apple', 'fruit'] },
      { emoji: '🍊', name: 'tangerine', keywords: ['orange', 'fruit'] },
      { emoji: '🍋', name: 'lemon', keywords: ['lemon', 'fruit', 'sour'] },
      { emoji: '🍇', name: 'grapes', keywords: ['grapes', 'fruit'] },
      { emoji: '🍓', name: 'strawberry', keywords: ['strawberry', 'fruit'] },
      { emoji: '🍒', name: 'cherries', keywords: ['cherry', 'fruit'] },
      { emoji: '🍑', name: 'peach', keywords: ['peach', 'fruit'] },
      { emoji: '🥭', name: 'mango', keywords: ['mango', 'fruit', 'tropical'] },
      { emoji: '🍍', name: 'pineapple', keywords: ['pineapple', 'tropical'] },
      { emoji: '🥥', name: 'coconut', keywords: ['coconut', 'tropical'] },
      { emoji: '🥝', name: 'kiwi fruit', keywords: ['kiwi', 'fruit'] },
      { emoji: '🍅', name: 'tomato', keywords: ['tomato', 'vegetable'] },
      { emoji: '🥑', name: 'avocado', keywords: ['avocado', 'guacamole'] },
      { emoji: '🌽', name: 'ear of corn', keywords: ['corn', 'vegetable'] },
      { emoji: '🌶️', name: 'hot pepper', keywords: ['pepper', 'spicy', 'hot'] },
      { emoji: '🥕', name: 'carrot', keywords: ['carrot', 'vegetable'] },
      { emoji: '🧅', name: 'onion', keywords: ['onion', 'vegetable'] },
      { emoji: '🥔', name: 'potato', keywords: ['potato', 'vegetable'] },
      { emoji: '🍞', name: 'bread', keywords: ['bread', 'toast'] },
      { emoji: '🥐', name: 'croissant', keywords: ['croissant', 'breakfast'] },
      { emoji: '🧀', name: 'cheese wedge', keywords: ['cheese', 'dairy'] },
      { emoji: '🥚', name: 'egg', keywords: ['egg', 'breakfast'] },
      { emoji: '🍳', name: 'cooking', keywords: ['egg', 'frying', 'breakfast'] },
      { emoji: '🥞', name: 'pancakes', keywords: ['pancakes', 'breakfast'] },
      { emoji: '🧇', name: 'waffle', keywords: ['waffle', 'breakfast'] },
      { emoji: '🥓', name: 'bacon', keywords: ['bacon', 'breakfast'] },
      { emoji: '🍗', name: 'poultry leg', keywords: ['chicken', 'meat'] },
      { emoji: '🍖', name: 'meat on bone', keywords: ['meat', 'bone'] },
      { emoji: '🌮', name: 'taco', keywords: ['taco', 'mexican'] },
      { emoji: '🌯', name: 'burrito', keywords: ['burrito', 'wrap'] },
      { emoji: '🥙', name: 'stuffed flatbread', keywords: ['pita', 'wrap'] },
      { emoji: '🍔', name: 'hamburger', keywords: ['burger', 'fast food'] },
      { emoji: '🍟', name: 'french fries', keywords: ['fries', 'fast food'] },
      { emoji: '🍕', name: 'pizza', keywords: ['pizza', 'italian'] },
      { emoji: '🌭', name: 'hot dog', keywords: ['hotdog', 'sausage'] },
      { emoji: '🥪', name: 'sandwich', keywords: ['sandwich', 'lunch'] },
      { emoji: '🍜', name: 'steaming bowl', keywords: ['noodles', 'ramen'] },
      { emoji: '🍝', name: 'spaghetti', keywords: ['pasta', 'italian'] },
      { emoji: '🍣', name: 'sushi', keywords: ['sushi', 'japanese'] },
      { emoji: '🍱', name: 'bento box', keywords: ['bento', 'japanese'] },
      { emoji: '🍦', name: 'soft ice cream', keywords: ['ice cream', 'dessert'] },
      { emoji: '🍰', name: 'shortcake', keywords: ['cake', 'dessert'] },
      { emoji: '🎂', name: 'birthday cake', keywords: ['cake', 'birthday'] },
      { emoji: '🍩', name: 'doughnut', keywords: ['donut', 'dessert'] },
      { emoji: '🍪', name: 'cookie', keywords: ['cookie', 'dessert'] },
      { emoji: '🍫', name: 'chocolate bar', keywords: ['chocolate', 'candy'] },
      { emoji: '🍬', name: 'candy', keywords: ['candy', 'sweet'] },
      { emoji: '🍭', name: 'lollipop', keywords: ['lollipop', 'candy'] },
      { emoji: '☕', name: 'hot beverage', keywords: ['coffee', 'tea', 'hot'] },
      { emoji: '🧋', name: 'bubble tea', keywords: ['boba', 'tea'] },
      { emoji: '🍵', name: 'teacup without handle', keywords: ['tea', 'green tea'] },
      { emoji: '🥤', name: 'cup with straw', keywords: ['drink', 'soda'] },
      { emoji: '🧃', name: 'beverage box', keywords: ['juice', 'drink'] },
      { emoji: '🍺', name: 'beer mug', keywords: ['beer', 'drink'] },
      { emoji: '🍷', name: 'wine glass', keywords: ['wine', 'drink'] },
      { emoji: '🥂', name: 'clinking glasses', keywords: ['champagne', 'celebrate'] },
      { emoji: '🍹', name: 'tropical drink', keywords: ['cocktail', 'tropical'] },
      { emoji: '🧉', name: 'mate', keywords: ['mate', 'drink'] },
      { emoji: '🥛', name: 'glass of milk', keywords: ['milk', 'drink'] },
      { emoji: '💧', name: 'droplet', keywords: ['water', 'drop'] },
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    icon: '⚽',
    emojis: [
      { emoji: '⚽', name: 'soccer ball', keywords: ['soccer', 'football', 'sport'] },
      { emoji: '🏀', name: 'basketball', keywords: ['basketball', 'sport'] },
      { emoji: '🏈', name: 'american football', keywords: ['football', 'sport'] },
      { emoji: '⚾', name: 'baseball', keywords: ['baseball', 'sport'] },
      { emoji: '🥎', name: 'softball', keywords: ['softball', 'sport'] },
      { emoji: '🎾', name: 'tennis', keywords: ['tennis', 'sport'] },
      { emoji: '🏐', name: 'volleyball', keywords: ['volleyball', 'sport'] },
      { emoji: '🏉', name: 'rugby football', keywords: ['rugby', 'sport'] },
      { emoji: '🥏', name: 'flying disc', keywords: ['frisbee', 'disc'] },
      { emoji: '🎱', name: 'pool 8 ball', keywords: ['billiards', 'pool'] },
      { emoji: '🏓', name: 'ping pong', keywords: ['ping pong', 'table tennis'] },
      { emoji: '🏸', name: 'badminton', keywords: ['badminton', 'sport'] },
      { emoji: '🥊', name: 'boxing glove', keywords: ['boxing', 'fight'] },
      { emoji: '🥋', name: 'martial arts uniform', keywords: ['karate', 'martial arts'] },
      { emoji: '🎯', name: 'bullseye', keywords: ['target', 'dart', 'aim'] },
      { emoji: '🎮', name: 'video game', keywords: ['game', 'controller', 'gaming'] },
      { emoji: '🕹️', name: 'joystick', keywords: ['game', 'joystick', 'arcade'] },
      { emoji: '🎲', name: 'game die', keywords: ['dice', 'game', 'random'] },
      { emoji: '🧩', name: 'puzzle piece', keywords: ['puzzle', 'jigsaw'] },
      { emoji: '🎭', name: 'performing arts', keywords: ['theater', 'drama'] },
      { emoji: '🎨', name: 'artist palette', keywords: ['art', 'paint', 'creative'] },
      { emoji: '🎬', name: 'clapper board', keywords: ['movie', 'film', 'action'] },
      { emoji: '🎤', name: 'microphone', keywords: ['mic', 'sing', 'karaoke'] },
      { emoji: '🎧', name: 'headphone', keywords: ['music', 'headphones', 'listen'] },
      { emoji: '🎵', name: 'musical note', keywords: ['music', 'note', 'song'] },
      { emoji: '🎶', name: 'musical notes', keywords: ['music', 'notes', 'song'] },
      { emoji: '🎸', name: 'guitar', keywords: ['guitar', 'music', 'rock'] },
      { emoji: '🎹', name: 'musical keyboard', keywords: ['piano', 'keyboard', 'music'] },
      { emoji: '🥁', name: 'drum', keywords: ['drum', 'music', 'beat'] },
      { emoji: '🎺', name: 'trumpet', keywords: ['trumpet', 'music'] },
      { emoji: '🎻', name: 'violin', keywords: ['violin', 'music'] },
      { emoji: '🏆', name: 'trophy', keywords: ['trophy', 'win', 'award'] },
      { emoji: '🥇', name: 'first place medal', keywords: ['gold', 'first', 'winner'] },
      { emoji: '🥈', name: 'second place medal', keywords: ['silver', 'second'] },
      { emoji: '🥉', name: 'third place medal', keywords: ['bronze', 'third'] },
      { emoji: '🎖️', name: 'military medal', keywords: ['medal', 'award'] },
      { emoji: '🎗️', name: 'reminder ribbon', keywords: ['ribbon', 'awareness'] },
      { emoji: '🎟️', name: 'admission tickets', keywords: ['ticket', 'event'] },
      { emoji: '🎪', name: 'circus tent', keywords: ['circus', 'carnival'] },
      { emoji: '🎠', name: 'carousel horse', keywords: ['carousel', 'fair'] },
      { emoji: '🎡', name: 'ferris wheel', keywords: ['ferris wheel', 'fair'] },
      { emoji: '🎢', name: 'roller coaster', keywords: ['roller coaster', 'fun'] },
    ],
  },
  {
    id: 'travel',
    label: 'Travel & Places',
    icon: '✈️',
    emojis: [
      { emoji: '🚗', name: 'automobile', keywords: ['car', 'drive', 'vehicle'] },
      { emoji: '🚕', name: 'taxi', keywords: ['taxi', 'cab'] },
      { emoji: '🚙', name: 'sport utility vehicle', keywords: ['suv', 'car'] },
      { emoji: '🚌', name: 'bus', keywords: ['bus', 'transport'] },
      { emoji: '🚎', name: 'trolleybus', keywords: ['trolley', 'bus'] },
      { emoji: '🏎️', name: 'racing car', keywords: ['race', 'car', 'fast'] },
      { emoji: '🚓', name: 'police car', keywords: ['police', 'cop'] },
      { emoji: '🚑', name: 'ambulance', keywords: ['ambulance', 'emergency'] },
      { emoji: '🚒', name: 'fire engine', keywords: ['fire truck', 'emergency'] },
      { emoji: '🚐', name: 'minibus', keywords: ['van', 'minibus'] },
      { emoji: '🚚', name: 'delivery truck', keywords: ['truck', 'delivery'] },
      { emoji: '🚛', name: 'articulated lorry', keywords: ['truck', 'semi'] },
      { emoji: '🚜', name: 'tractor', keywords: ['tractor', 'farm'] },
      { emoji: '🏍️', name: 'motorcycle', keywords: ['motorcycle', 'bike'] },
      { emoji: '🛵', name: 'motor scooter', keywords: ['scooter', 'moped'] },
      { emoji: '🚲', name: 'bicycle', keywords: ['bike', 'cycle'] },
      { emoji: '🛴', name: 'kick scooter', keywords: ['scooter', 'kick'] },
      { emoji: '🛹', name: 'skateboard', keywords: ['skateboard', 'skate'] },
      { emoji: '🚁', name: 'helicopter', keywords: ['helicopter', 'chopper'] },
      { emoji: '✈️', name: 'airplane', keywords: ['plane', 'fly', 'travel'] },
      { emoji: '🚀', name: 'rocket', keywords: ['rocket', 'space', 'launch'] },
      { emoji: '🛸', name: 'flying saucer', keywords: ['ufo', 'alien', 'space'] },
      { emoji: '🚢', name: 'ship', keywords: ['ship', 'boat', 'cruise'] },
      { emoji: '⛵', name: 'sailboat', keywords: ['sail', 'boat'] },
      { emoji: '🚤', name: 'speedboat', keywords: ['boat', 'speed'] },
      { emoji: '🏖️', name: 'beach with umbrella', keywords: ['beach', 'vacation'] },
      { emoji: '🏝️', name: 'desert island', keywords: ['island', 'tropical'] },
      { emoji: '🏔️', name: 'snow-capped mountain', keywords: ['mountain', 'snow'] },
      { emoji: '🗻', name: 'mount fuji', keywords: ['fuji', 'mountain', 'japan'] },
      { emoji: '🌋', name: 'volcano', keywords: ['volcano', 'eruption'] },
      { emoji: '🏕️', name: 'camping', keywords: ['camping', 'tent', 'outdoor'] },
      { emoji: '🌍', name: 'globe showing europe-africa', keywords: ['earth', 'world', 'globe'] },
      { emoji: '🌎', name: 'globe showing americas', keywords: ['earth', 'world', 'globe'] },
      { emoji: '🌏', name: 'globe showing asia-australia', keywords: ['earth', 'world', 'globe'] },
      { emoji: '🗺️', name: 'world map', keywords: ['map', 'world', 'travel'] },
      { emoji: '🗼', name: 'tokyo tower', keywords: ['tokyo', 'japan', 'tower'] },
      { emoji: '🗽', name: 'statue of liberty', keywords: ['liberty', 'new york', 'usa'] },
      { emoji: '🏰', name: 'european castle', keywords: ['castle', 'medieval'] },
      { emoji: '🏯', name: 'japanese castle', keywords: ['castle', 'japan'] },
      { emoji: '🎡', name: 'ferris wheel', keywords: ['ferris wheel', 'fair'] },
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icon: '💡',
    emojis: [
      { emoji: '⌚', name: 'watch', keywords: ['watch', 'time', 'clock'] },
      { emoji: '📱', name: 'mobile phone', keywords: ['phone', 'mobile', 'cell'] },
      { emoji: '💻', name: 'laptop', keywords: ['laptop', 'computer', 'mac'] },
      { emoji: '⌨️', name: 'keyboard', keywords: ['keyboard', 'type'] },
      { emoji: '🖥️', name: 'desktop computer', keywords: ['computer', 'desktop', 'monitor'] },
      { emoji: '🖨️', name: 'printer', keywords: ['printer', 'print'] },
      { emoji: '🖱️', name: 'computer mouse', keywords: ['mouse', 'click'] },
      { emoji: '📷', name: 'camera', keywords: ['camera', 'photo', 'picture'] },
      { emoji: '📸', name: 'camera with flash', keywords: ['camera', 'flash', 'photo'] },
      { emoji: '📹', name: 'video camera', keywords: ['video', 'camera', 'record'] },
      { emoji: '📺', name: 'television', keywords: ['tv', 'television', 'watch'] },
      { emoji: '📻', name: 'radio', keywords: ['radio', 'music'] },
      { emoji: '🎙️', name: 'studio microphone', keywords: ['mic', 'podcast', 'record'] },
      { emoji: '📞', name: 'telephone receiver', keywords: ['phone', 'call'] },
      { emoji: '☎️', name: 'telephone', keywords: ['phone', 'call', 'old'] },
      { emoji: '📟', name: 'pager', keywords: ['pager', 'beeper'] },
      { emoji: '📠', name: 'fax machine', keywords: ['fax', 'machine'] },
      { emoji: '🔋', name: 'battery', keywords: ['battery', 'power', 'charge'] },
      { emoji: '🔌', name: 'electric plug', keywords: ['plug', 'power', 'electric'] },
      { emoji: '💡', name: 'light bulb', keywords: ['idea', 'light', 'bulb'] },
      { emoji: '🔦', name: 'flashlight', keywords: ['flashlight', 'torch', 'light'] },
      { emoji: '🕯️', name: 'candle', keywords: ['candle', 'light', 'flame'] },
      { emoji: '🗑️', name: 'wastebasket', keywords: ['trash', 'delete', 'bin'] },
      { emoji: '🔑', name: 'key', keywords: ['key', 'lock', 'access'] },
      { emoji: '🗝️', name: 'old key', keywords: ['key', 'old', 'lock'] },
      { emoji: '🔒', name: 'locked', keywords: ['lock', 'secure', 'private'] },
      { emoji: '🔓', name: 'unlocked', keywords: ['unlock', 'open', 'access'] },
      { emoji: '🔨', name: 'hammer', keywords: ['hammer', 'tool', 'build'] },
      { emoji: '⚒️', name: 'hammer and pick', keywords: ['tools', 'build'] },
      { emoji: '🛠️', name: 'hammer and wrench', keywords: ['tools', 'fix', 'repair'] },
      { emoji: '⚙️', name: 'gear', keywords: ['gear', 'settings', 'cog'] },
      { emoji: '🔧', name: 'wrench', keywords: ['wrench', 'tool', 'fix'] },
      { emoji: '🔩', name: 'nut and bolt', keywords: ['bolt', 'nut', 'tool'] },
      { emoji: '🧲', name: 'magnet', keywords: ['magnet', 'attract'] },
      { emoji: '💊', name: 'pill', keywords: ['pill', 'medicine', 'drug'] },
      { emoji: '💉', name: 'syringe', keywords: ['syringe', 'injection', 'vaccine'] },
      { emoji: '🩺', name: 'stethoscope', keywords: ['doctor', 'medical', 'health'] },
      { emoji: '🩹', name: 'adhesive bandage', keywords: ['bandage', 'hurt', 'heal'] },
      { emoji: '📚', name: 'books', keywords: ['books', 'read', 'study'] },
      { emoji: '📖', name: 'open book', keywords: ['book', 'read', 'open'] },
      { emoji: '📝', name: 'memo', keywords: ['note', 'write', 'memo'] },
      { emoji: '✏️', name: 'pencil', keywords: ['pencil', 'write', 'draw'] },
      { emoji: '🖊️', name: 'pen', keywords: ['pen', 'write'] },
      { emoji: '📌', name: 'pushpin', keywords: ['pin', 'location', 'mark'] },
      { emoji: '📎', name: 'paperclip', keywords: ['paperclip', 'attach'] },
      { emoji: '✂️', name: 'scissors', keywords: ['scissors', 'cut'] },
      { emoji: '🗂️', name: 'card index dividers', keywords: ['folder', 'organize'] },
      { emoji: '📁', name: 'file folder', keywords: ['folder', 'file'] },
      { emoji: '📂', name: 'open file folder', keywords: ['folder', 'open', 'file'] },
      { emoji: '🗃️', name: 'card file box', keywords: ['box', 'file', 'organize'] },
      { emoji: '📦', name: 'package', keywords: ['box', 'package', 'delivery'] },
      { emoji: '📫', name: 'closed mailbox with raised flag', keywords: ['mail', 'mailbox'] },
      { emoji: '📬', name: 'open mailbox with raised flag', keywords: ['mail', 'mailbox'] },
      { emoji: '📭', name: 'open mailbox with lowered flag', keywords: ['mail', 'empty'] },
      { emoji: '📮', name: 'postbox', keywords: ['mail', 'post'] },
      { emoji: '🗳️', name: 'ballot box with ballot', keywords: ['vote', 'ballot'] },
      { emoji: '✉️', name: 'envelope', keywords: ['email', 'mail', 'letter'] },
      { emoji: '📧', name: 'e-mail', keywords: ['email', 'mail'] },
      { emoji: '💬', name: 'speech balloon', keywords: ['chat', 'message', 'talk'] },
      { emoji: '💭', name: 'thought balloon', keywords: ['think', 'thought'] },
      { emoji: '🔔', name: 'bell', keywords: ['bell', 'notification', 'alert'] },
      { emoji: '🔕', name: 'bell with slash', keywords: ['mute', 'silent', 'no bell'] },
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '✅',
    emojis: [
      { emoji: '✅', name: 'check mark button', keywords: ['check', 'yes', 'done', 'ok'] },
      { emoji: '❌', name: 'cross mark', keywords: ['no', 'wrong', 'x', 'cancel'] },
      { emoji: '❓', name: 'question mark', keywords: ['question', 'what', 'huh'] },
      { emoji: '❗', name: 'exclamation mark', keywords: ['exclamation', 'important'] },
      { emoji: '‼️', name: 'double exclamation mark', keywords: ['important', 'urgent'] },
      { emoji: '⁉️', name: 'exclamation question mark', keywords: ['what', 'surprised'] },
      { emoji: '💯', name: 'hundred points', keywords: ['100', 'perfect', 'score'] },
      { emoji: '🔝', name: 'top arrow', keywords: ['top', 'up'] },
      { emoji: '🆗', name: 'ok button', keywords: ['ok', 'okay'] },
      { emoji: '🆕', name: 'new button', keywords: ['new', 'fresh'] },
      { emoji: '🆙', name: 'up button', keywords: ['up', 'upgrade'] },
      { emoji: '🆒', name: 'cool button', keywords: ['cool'] },
      { emoji: '🆓', name: 'free button', keywords: ['free'] },
      { emoji: '🆖', name: 'ng button', keywords: ['ng', 'no good'] },
      { emoji: '🅰️', name: 'a button', keywords: ['a', 'blood type'] },
      { emoji: '🅱️', name: 'b button', keywords: ['b', 'blood type'] },
      { emoji: '🆎', name: 'ab button', keywords: ['ab', 'blood type'] },
      { emoji: '🆑', name: 'cl button', keywords: ['cl', 'clear'] },
      { emoji: '🅾️', name: 'o button', keywords: ['o', 'blood type'] },
      { emoji: '🆘', name: 'sos button', keywords: ['sos', 'help', 'emergency'] },
      { emoji: '⛔', name: 'no entry', keywords: ['no', 'stop', 'forbidden'] },
      { emoji: '🚫', name: 'prohibited', keywords: ['no', 'forbidden', 'ban'] },
      { emoji: '🚷', name: 'no pedestrians', keywords: ['no', 'pedestrian'] },
      { emoji: '🚯', name: 'no littering', keywords: ['no', 'litter'] },
      { emoji: '🚳', name: 'no bicycles', keywords: ['no', 'bike'] },
      { emoji: '🚱', name: 'non-potable water', keywords: ['no', 'water'] },
      { emoji: '📵', name: 'no mobile phones', keywords: ['no', 'phone'] },
      { emoji: '🔞', name: 'no one under eighteen', keywords: ['18', 'adult', 'nsfw'] },
      { emoji: '♻️', name: 'recycling symbol', keywords: ['recycle', 'green', 'eco'] },
      { emoji: '✔️', name: 'check mark', keywords: ['check', 'done', 'yes'] },
      { emoji: '🔃', name: 'clockwise vertical arrows', keywords: ['refresh', 'reload'] },
      { emoji: '🔄', name: 'counterclockwise arrows button', keywords: ['refresh', 'reload', 'sync'] },
      { emoji: '🔙', name: 'back arrow', keywords: ['back', 'return'] },
      { emoji: '🔚', name: 'end arrow', keywords: ['end'] },
      { emoji: '🔛', name: 'on arrow', keywords: ['on'] },
      { emoji: '🔜', name: 'soon arrow', keywords: ['soon'] },
      { emoji: '⬆️', name: 'up arrow', keywords: ['up', 'arrow'] },
      { emoji: '⬇️', name: 'down arrow', keywords: ['down', 'arrow'] },
      { emoji: '⬅️', name: 'left arrow', keywords: ['left', 'arrow'] },
      { emoji: '➡️', name: 'right arrow', keywords: ['right', 'arrow'] },
      { emoji: '↗️', name: 'up-right arrow', keywords: ['up', 'right', 'arrow'] },
      { emoji: '↘️', name: 'down-right arrow', keywords: ['down', 'right', 'arrow'] },
      { emoji: '↙️', name: 'down-left arrow', keywords: ['down', 'left', 'arrow'] },
      { emoji: '↖️', name: 'up-left arrow', keywords: ['up', 'left', 'arrow'] },
      { emoji: '↕️', name: 'up-down arrow', keywords: ['up', 'down', 'arrow'] },
      { emoji: '↔️', name: 'left-right arrow', keywords: ['left', 'right', 'arrow'] },
      { emoji: '🔀', name: 'shuffle tracks button', keywords: ['shuffle', 'random'] },
      { emoji: '🔁', name: 'repeat button', keywords: ['repeat', 'loop'] },
      { emoji: '🔂', name: 'repeat single button', keywords: ['repeat', 'once'] },
      { emoji: '▶️', name: 'play button', keywords: ['play', 'start'] },
      { emoji: '⏸️', name: 'pause button', keywords: ['pause', 'stop'] },
      { emoji: '⏹️', name: 'stop button', keywords: ['stop'] },
      { emoji: '⏺️', name: 'record button', keywords: ['record'] },
      { emoji: '⏭️', name: 'next track button', keywords: ['next', 'skip'] },
      { emoji: '⏮️', name: 'last track button', keywords: ['previous', 'back'] },
      { emoji: '🔊', name: 'speaker high volume', keywords: ['loud', 'volume', 'sound'] },
      { emoji: '🔉', name: 'speaker medium volume', keywords: ['volume', 'sound'] },
      { emoji: '🔈', name: 'speaker low volume', keywords: ['quiet', 'volume'] },
      { emoji: '🔇', name: 'muted speaker', keywords: ['mute', 'silent', 'no sound'] },
      { emoji: '📣', name: 'megaphone', keywords: ['megaphone', 'loud', 'announce'] },
      { emoji: '📢', name: 'loudspeaker', keywords: ['speaker', 'announce'] },
      { emoji: '🔔', name: 'bell', keywords: ['bell', 'notification'] },
      { emoji: '🔕', name: 'bell with slash', keywords: ['mute', 'no bell'] },
      { emoji: '🎵', name: 'musical note', keywords: ['music', 'note'] },
      { emoji: '🎶', name: 'musical notes', keywords: ['music', 'notes'] },
      { emoji: '💤', name: 'zzz', keywords: ['sleep', 'zzz', 'tired'] },
      { emoji: '🔥', name: 'fire', keywords: ['fire', 'hot', 'lit'] },
      { emoji: '💥', name: 'collision', keywords: ['boom', 'explosion', 'bang'] },
      { emoji: '💫', name: 'dizzy', keywords: ['dizzy', 'star', 'spin'] },
      { emoji: '⚡', name: 'high voltage', keywords: ['lightning', 'electric', 'zap'] },
      { emoji: '🌀', name: 'cyclone', keywords: ['cyclone', 'spin', 'dizzy'] },
      { emoji: '🌈', name: 'rainbow', keywords: ['rainbow', 'colorful'] },
      { emoji: '💦', name: 'sweat droplets', keywords: ['sweat', 'water', 'splash'] },
      { emoji: '💨', name: 'dashing away', keywords: ['wind', 'fast', 'dash'] },
    ],
  },
];

export const allEmojis: EmojiItem[] = emojiCategories.flatMap((cat) => cat.emojis);
